=== RoyCurtis/RAG/data/phrases.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="urn:RAG.Phrases"
           xmlns="urn:RAG.Phrases"
           elementFormDefault="qualified">

<xs:annotation>
  <xs:documentation>
    This schema describes how the RAG phrases data is structured, to help validation.
    I have written a lot of comments here, because XSD can be confusing and verbose.

    Schema by Roy Curtis, 2018, MIT licensed.
  </xs:documentation>
</xs:annotation>

<!-- Root tag -->

<xs:element name="messages">
  <xs:annotation>
    <xs:documentation>
      Holds a collection of phrases and phrasesets. Each one must have an `id` to be
      referenced by, elsewhere.
    </xs:documentation>
  </xs:annotation>

  <xs:complexType>
    <!-- Allow unlimited mixed collection of phrase and phrasesets -->
    <xs:choice maxOccurs="unbounded">
      <xs:element name="phraseset" type="phraseset_def"/>
      <xs:element name="phrase" type="phrase_root_def"/>
    </xs:choice>
  </xs:complexType>
</xs:element>

<!-- Defining types -->

<xs:complexType name="phraseset_def">
  <xs:annotation>
    <xs:documentation>
      Represents a collection of related phrases, that will either be picked randomly from
      or chosen by the user from a list.
    </xs:documentation>
  </xs:annotation>

  <!-- Allow unlimited amount of phrase elements, but require at least one -->
  <xs:sequence>
    <xs:element name="phrase" type="phrase_def" maxOccurs="unbounded"/>
  </xs:sequence>

  <xs:attribute name="id" type="xs:string" use="required">
    <xs:annotation>
      <xs:documentation>
        Unique ID to give this phraseset, to be referenced from within other phrases.
      </xs:documentation>
    </xs:annotation>
  </xs:attribute>
</xs:complexType>


<xs:complexType name="phrase_def" mixed="true">
  <xs:annotation>
    <xs:documentation>
      Represents a phrase made up of text content and "reference" tags, that tell RAG
      where to slot in specific types of generated or chosen data.
    </xs:documentation>
  </xs:annotation>

  <!-- Allow unlimited amount of acceptable inner elements, or just text -->
  <xs:group ref="phrase_elements" minOccurs="0" maxOccurs="unbounded"/>

  <xs:attribute name="id" type="xs:string">
    <xs:annotation>
      <xs:documentation>
        Unique ID to give this phrase, to be referenced from within other phrases.
      </xs:documentation>
    </xs:annotation>
  </xs:attribute>
</xs:complexType>


<xs:complexType name="phrase_root_def">
  <xs:annotation>
    <xs:documentation>
      Represents a phrase that's a direct child of the root tag. `id` is required, so that
      it can be referenced from within other phrases.
    </xs:documentation>
  </xs:annotation>

  <!-- Extends from phrase_def, to make the id attribute required -->
  <xs:complexContent>
    <xs:extension base="phrase_def">
      <xs:attribute name="id" type="xs:string" use="required"/>
    </xs:extension>
  </xs:complexContent>
</xs:complexType>

<!-- Elements -->

<xs:group name="phrase_elements">
  <xs:choice>
    <xs:element name="coach">
      <xs:annotation>
        <xs:documentation>
          Picks a coach letter from A to Z, limited by amount of coaches.
        </xs:documentation>
      </xs:annotation>
    </xs:element>

    <xs:element name="excuse">
      <xs:annotation>
        <xs:documentation>
          Picks an excuse for a delay or cancellation.
        </xs:documentation>
      </xs:annotation>
    </xs:element>

    <xs:element name="integer" type="integer">
      <xs:annotation>
        <xs:documentation>
          Picks a whole number, with optional limits, noun and in word form.
        </xs:documentation>
      </xs:annotation>
    </xs:element>

    <xs:element name="named">
      <xs:annotation>
        <xs:documentation>
          Picks a named train.
        </xs:documentation>
      </xs:annotation>
    </xs:element>

    <xs:element name="phrase" type="phrase_ref">
      <xs:annotation>
        <xs:documentation>
          Includes a previously defined phrase, by its `id`.
        </xs:documentation>
      </xs:annotation>
    </xs:element>

    <xs:element name="phraseset" type="phraseset_ref">
      <xs:annotation>
        <xs:documentation>
          Picks a phrase from a previously defined phraseset, by its `id`.
        </xs:documentation>
      </xs:annotation>
    </xs:element>

    <xs:element name="platform">
      <xs:annotation>
        <xs:documentation>
          Picks a platform number, sometimes with letter.
        </xs:documentation>
      </xs:annotation>
    </xs:element>

    <xs:element name="service">
      <xs:annotation>
        <xs:documentation>
          Picks a rail network name.
        </xs:documentation>
      </xs:annotation>
    </xs:element>

    <xs:element name="station" type="station">
      <xs:annotation>
        <xs:documentation>
          Picks a station name.
        </xs:documentation>
      </xs:annotation>
    </xs:element>

    <xs:element name="stationlist" type="stationlist">
      <xs:annotation>
        <xs:documentation>
          Picks a selection of stations.
        </xs:documentation>
      </xs:annotation>
    </xs:element>

    <xs:element name="time">
      <xs:annotation>
        <xs:documentation>
          Picks a 24 hour time, with hours and minutes.
        </xs:documentation>
      </xs:annotation>
    </xs:element>
  </xs:choice>
</xs:group>


<xs:complexType name="integer">
  <xs:attribute name="min" type="xs:int" use="required"/>
  <xs:attribute name="max" type="xs:int" use="required"/>

  <xs:attribute name="id" type="xs:string" use="required">
    <xs:annotation>
      <xs:documentation>
        Unique ID to give this integer, for state tracking.
      </xs:documentation>
    </xs:annotation>
  </xs:attribute>

  <xs:attribute name="singular" type="xs:string">
    <xs:annotation>
      <xs:documentation>
        Optional noun to append after chosen integer, if it is one.
      </xs:documentation>
    </xs:annotation>
  </xs:attribute>

  <xs:attribute name="plural" type="xs:string">
    <xs:annotation>
      <xs:documentation>
        Optional noun to append after chosen integer, if it is many.
      </xs:documentation>
    </xs:annotation>
  </xs:attribute>

  <xs:attribute name="words" type="xs:boolean" default="false">
    <xs:annotation>
      <xs:documentation>
        If true, the integer is printed as a word, than in digits.
      </xs:documentation>
    </xs:annotation>
  </xs:attribute>
</xs:complexType>


<xs:complexType name="phrase_ref">
  <xs:attribute name="ref" type="xs:string" use="required">
    <xs:annotation>
      <xs:documentation>
        Must be a valid `id` of a previously defined phrase.
      </xs:documentation>
    </xs:annotation>
  </xs:attribute>

  <xs:attribute name="chance" type="chance"/>
</xs:complexType>


<xs:complexType name="phraseset_ref">
  <xs:attribute name="ref" type="xs:string" use="required">
    <xs:annotation>
      <xs:documentation>
        Must be a valid `id` of a previously defined phraseset.
      </xs:documentation>
    </xs:annotation>
  </xs:attribute>

  <xs:attribute name="op" type="phraseset_ref_op" default="random">
    <xs:annotation>
      <xs:documentation>
        Optionally specifies how a phrase should be picked from this set.
      </xs:documentation>
    </xs:annotation>
  </xs:attribute>

  <xs:attribute name="chance" type="chance"/>
</xs:complexType>


<xs:complexType name="station">
  <xs:attribute name="context" type="station_context" use="required">
    <xs:annotation>
      <xs:documentation>
        Specifies the context to pick a station for.
      </xs:documentation>
    </xs:annotation>
  </xs:attribute>
</xs:complexType>


<xs:complexType name="stationlist">
  <!-- TODO: change this to "context" -->
  <!-- TODO: should there be a "config" element to define list types and limits? -->
  <xs:attribute name="id" type="xs:string" use="required">
    <xs:annotation>
      <xs:documentation>
        Defines an `id` for the list to create, or to repeat if already exists.
      </xs:documentation>
    </xs:annotation>
  </xs:attribute>

  <xs:attribute name="min" type="xs:int" default="1"/>
  <xs:attribute name="max" type="xs:int" default="16"/>
</xs:complexType>

<!-- Value types -->

<xs:simpleType name="chance">
  <xs:annotation>
    <xs:documentation>
      An integer between 0 and 100; percent likelihood this element will appear.
    </xs:documentation>
  </xs:annotation>

  <xs:restriction base="xs:int">
    <xs:minInclusive value="0"/>
    <xs:maxInclusive value="100"/>
  </xs:restriction>
</xs:simpleType>


<xs:simpleType name="station_context">
  <xs:restriction base="xs:string">
    <xs:enumeration value="calling">
      <xs:annotation>
        <xs:documentation>
          Picks a station from the calling list, excluding the final stop.
        </xs:documentation>
      </xs:annotation>
    </xs:enumeration>

    <xs:enumeration value="destination">
      <xs:annotation>
        <xs:documentation>
          Picks the station that's the final stop of a calling list, or at random.
        </xs:documentation>
      </xs:annotation>
    </xs:enumeration>

    <xs:enumeration value="destination2">
      <xs:annotation>
        <xs:documentation>
          For a split train, picks the station that's the final stop of the second half
          of a calling list, or at random.
        </xs:documentation>
      </xs:annotation>
    </xs:enumeration>

    <xs:enumeration value="via">
      <xs:annotation>
        <xs:documentation>
          Picks a station in the middle of a calling list, as a "via" stop.
        </xs:documentation>
      </xs:annotation>
    </xs:enumeration>

    <xs:enumeration value="via2">
      <xs:annotation>
        <xs:documentation>
          For a split train, picks a station in the middle of the second half of a calling
          list, as a "via" stop.
        </xs:documentation>
      </xs:annotation>
    </xs:enumeration>

    <xs:enumeration value="random">
      <xs:annotation>
        <xs:documentation>
          Picks a random station not on any calling list or other contexts.
        </xs:documentation>
      </xs:annotation>
    </xs:enumeration>

    <xs:enumeration value="source">
      <xs:annotation>
        <xs:documentation>
          Picks a station not on any calling list, as a "from" stop.
        </xs:documentation>
      </xs:annotation>
    </xs:enumeration>
  </xs:restriction>
</xs:simpleType>


<xs:simpleType name="phraseset_ref_op">
  <xs:restriction base="xs:string">
    <xs:enumeration value="random">
      <xs:annotation>
        <xs:documentation>
          Picks a phrase from the phraseset at random.
        </xs:documentation>
      </xs:annotation>
    </xs:enumeration>

    <xs:enumeration value="cycle">
      <xs:annotation>
        <xs:documentation>
          Picks the next phrase from the phraseset, cycling back to the beginning if the
          end of the set is reached. If one hadn't been picked before, defaults to random.
        </xs:documentation>
      </xs:annotation>
    </xs:enumeration>

    <xs:enumeration value="repeat">
      <xs:annotation>
        <xs:documentation>
          Repeats the last phrase that was picked from the phraseset. If one hadn't been
          picked before, defaults to random.
        </xs:documentation>
      </xs:annotation>
    </xs:enumeration>
  </xs:restriction>
</xs:simpleType>

</xs:schema>

=== RoyCurtis/RAG/data/phrases.xml
<?xml version="1.0" encoding="utf-8"?>
<messages xmlns="urn:RAG.Phrases"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="urn:RAG.Phrases ./phrases.xsd" >

<!--
  Although the XML structure and schema are my work, please assume the contents of this
  XML (especially the phrases themselves) are copyright of National Rail. Unlicensed.

  Sources for these phrases:

  * https://youtube.com/watch?v=ftiB6HLjWCM (Crewe)
  * https://youtube.com/watch?v=14B_6H5QusI (Reading)
  * https://youtube.com/watch?v=OOUQ0V7wS5U (Shrewsbury)
  * https://youtube.com/watch?v=v-eqKjbXlaw (Southampton)
  * https://youtube.com/watch?v=2Qe6PRLTvnI (Swindon)
  * https://www.scribd.com/document/105631178/National-Rail-Delay-Phrases

  See also the `ref` folder.
-->

<!-- Main set of phrases -->

<phraseset id="root">
  <!-- Train waiting at platform -->
  <phrase>
    <phraseset ref="platform_wait_intro"/>
    <phraseset ref="calling_at" chance="50"/>
    <phraseset ref="mind_the_gap" chance="5"/>
    <phraseset ref="change_at" chance="5"/>
    <phrase ref="not_stopping" chance="5"/>
    <phraseset ref="request_stop" chance="5"/>
    <phraseset ref="trolley_service" chance="5"/>
    <phrase ref="coach_count" chance="90"/>
    <phraseset ref="shop_service" chance="5"/>
    <phrase ref="train_full" chance="5"/>
    <phraseset ref="train_layout" chance="5"/>
    <phraseset ref="train_seating" chance="5"/>
    <phrase ref="platform_wait" chance="50" />.
  </phrase>

  <!-- Train departing from platform -->
  <phrase>
    The train at platform <platform/> is <phrase ref="service_to"/>.
    <phraseset ref="calling_at"/> Will passengers intending to travel on this service
    please join the train now, as it is ready to leave. <phrase ref="platform_wait"/>,
    which is ready to leave.
  </phrase>

  <!-- Terminating train -->
  <phrase>
    Platform <platform/> for the <phrase ref="service"/> from <station/>. This train will
    terminate here.
  </phrase>

  <!-- Delayed and cancelled trains -->
  <phrase>
    <phrase ref="attention_please_platform" chance="25"/>
    <phraseset ref="apology_begin"/> <phrase ref="service"/> to
    <phrase ref="destination"/><phraseset ref="delayed_or_cancelled"/>
  </phrase>

  <phrase>
    We are sorry that services are subject to delay because of <excuse/>.
    <phraseset ref="general_apology_delay" chance="50"/>
  </phrase>

  <!-- Platform alterations -->
  <phrase>
    This is a platform alteration. The <phrase ref="service"/>
    <phraseset ref="destination_from_to"/>, will now <phraseset ref="depart_arrive"/>
    platform <platform/>.
  </phrase>

  <!-- Non-stop trains -->
  <phrase>
    The train now approaching platform <platform/> does not stop here. Stand back from the
    edge of platform <platform/>. The next train is not scheduled to stop.
  </phrase>

  <!-- Out of service trains -->
  <phrase>
    The next train to arrive at platform <platform/> is not in passenger service. Please
    do not board the next train at platform <platform/>.
  </phrase>

  <!-- Various notices and reminders (e.g. security) -->
  <phrase>
    <phrase ref="attention_please" chance="10"/> <phraseset ref="notices"/>
  </phrase>
</phraseset>

<!-- Main set of notices -->

<phraseset id="notices">
  <phrase>
    Please note, to ensure a timely departure, train doors will be locked shut up to 40
    seconds before departure. Thank you.
  </phrase>
  <phrase>
    For your safety and comfort, this station operates a no-smoking policy.
  </phrase>
  <phrase>
    Smoking is not permitted at this station.
  </phrase>
  <phrase>
    All of our trains and stations are no-smoking areas. Please do not smoke until you
    have left the station premesis.
  </phrase>
  <phrase>
    24 hour C.C.T.V. recording is in operation at this station for the purpose of security
    and safety management.
  </phrase>
  <phrase>
    Closed circuit television and remote video monitoring is in use at this station for
    your personal safety and security.
  </phrase>
  <phrase>
    Please do not leave your personal belongings unattended on the station. Any personal
    belongings left unattended may be removed without warning, or destroyed or damaged by
    the security services.
  </phrase>
  <phrase>
    Please do not leave your luggage unattended on the station. Luggage left unattended
    may be removed without warning, or destroyed or damaged by the security services.
  </phrase>
  <phrase>
    Penalty fares apply across the entire <service/> network. Please ensure that you buy
    your ticket before you board, where facilities are available.
  </phrase>
  <phrase>
    This is a security message. If you see something that doesn't look right, speak to
    staff or text the British Transport Police on 61016. We'll sort it. See it, say it,
    sorted.
  </phrase>
  <phrase>
    This is a safety announcement. Please take care when using the escalators located on
    this station. If you have luggage or a bicycle, then please use the passenger lifts
    and ask for assistance if you need it. Thank you.
  </phrase>
  <phrase>
    In the interests of safety, the riding of skateboards, rollerblades, and cycles on
    this station are prohibited. Offenders may be prosecuted under the railway bylaw
    number 30.
  </phrase>
</phraseset>

<!-- Various parts of other phrases -->

<phrase id="attention_please">
  May I have your attention please.
</phrase>

<phrase id="attention_please_platform">
  May I have your attention please on platform <platform/>.
</phrase>

<phraseset id="platform_wait_intro">
  <phrase>
    <phrase ref="platform_wait"/>.
  </phrase>
  <phrase>
    The next train to <phraseset ref="depart_arrive"/> platform <platform/> will be
    <phrase ref="service_to"/>.
  </phrase>
  <phrase>
    The train now approaching platform <platform/> is <phrase ref="service_to"/>.
    <phrase ref="service_from" chance="50"/>
  </phrase>
</phraseset>

<phrase id="platform_wait">
  Platform <platform/> for the <phrase ref="service"/> to <phrase ref="destination"/>
</phrase>

<phrase id="destination">
  <station context="destination"/>
  <optional chance="10">via <station context="via"/></optional>
  <optional chance="5">
    and <station context="destination2"/>
    <optional chance="10">via <station context="via2"/></optional>
  </optional>
</phrase>

<phrase id="service_to">
  the <optional chance="5">delayed</optional> <phrase ref="service"/> to
  <phrase ref="destination"/>
</phrase>

<phrase id="service">
  <optional chance="5"><named />, the</optional> <time/>
  <optional chance="90"><service/></optional> service
</phrase>

<phrase id="service_from">
  This is the service from <station context="source"/>.
</phrase>

<phraseset id="calling_at">
  <phrase>Calling at <stationlist id="calling"/>.</phrase>
  <phrase>
    For <stationlist id="calling_half1"/>, travel in the front <integer min="2" max="5"/>
    coaches of the train. And for <stationlist id="calling_half2"/>, travel in the rear
    <integer min="2" max="5"/> coaches of the train.
  </phrase>
</phraseset>

<phraseset id="mind_the_gap">
  <phrase>
    Mind the gap between the train and the platform. Mind the gap.
  </phrase>
  <phrase>
    When boarding the train, please mind the gap between the train and the platform edge.
  </phrase>
</phraseset>

<phraseset id="apology_begin">
  <phrase>We are sorry to announce that the</phrase>
  <phrase>We are sorry that the</phrase>
</phraseset>

<phraseset id="delayed_or_cancelled">
  <phrase>
    is delayed
    <optional>
      by approximately <integer min="5" max="120" plural="minutes"/>
    </optional><phraseset ref="excuse_or_wait" chance="50"/>
    <phraseset ref="service_apology_delay" chance="50"/>
  </phrase>
  <phrase>
    has been cancelled <phraseset ref="excuse_or_wait" chance="50"/>
    <phraseset ref="service_apology" chance="50"/>
  </phrase>
</phraseset>

<phraseset id="excuse_pre">
  <phrase>, </phrase>
  <phrase>. This is </phrase>
</phraseset>

<phrase id="excuse">
  <phraseset ref="excuse_pre"/>due to <excuse/>
  <optional chance="50"> <phraseset ref="at_near"/> <station/></optional>.
</phrase>

<phraseset id="excuse_or_wait">
  <phrase><phrase ref="excuse"/></phrase>
  <phrase>. Please listen for further announcements.</phrase>
</phraseset>

<phraseset id="general_apology_delay">
  <phrase>National Rail apologises for this delay.</phrase>
  <phrase>We apologise for the inconvenience this may cause you.</phrase>
</phraseset>

<phraseset id="service_apology_delay">
  <phrase><service/> apologises for this delay.</phrase>
  <phrase><phraseset ref="general_apology_delay"/></phrase>
  <phrase><phraseset ref="service_apology"/></phrase>
</phraseset>

<phraseset id="service_apology">
  <phrase>We apologise for the inconvenience this may cause you.</phrase>
  <phrase>We apologise for the disruption to your journey today.</phrase>
  <phrase><service/> apologises for the disruption to your journey today.</phrase>
</phraseset>

<phraseset id="change_at">
  <phrase>
    Customers for <stationlist id="changes" max="4"/> should change at
    <station list="calling"/>.
  </phrase>
  <phrase>
    Change at <station list="calling"/> for the services to
    <stationlist id="changes" max="4"/>.
  </phrase>
</phraseset>

<phrase id="not_stopping">
  This train will not be calling at <stationlist id="not_stopping" max="8"/> today
  <phrase ref="excuse"/>
</phrase>

<phraseset id="request_stop">
  <phrase>
    <station list="calling"/> is a request stop, and passengers for this station should
    ask the conductor on the train to arrange for the train to stop, to allow them to
    <phraseset ref="leave"/>.
  </phrase>
  <phrase>
    <stationlist id="request"/> are request stops, and passengers for these stations
    should ask the conductor on the train to arrange for the train to stop, to allow them
    to <phraseset ref="leave"/>.
  </phrase>
</phraseset>

<phraseset id="trolley_service">
  <phrase>
